# -*- coding: utf-8 -*-
"""sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/142E9TtIsvsOFLjrTUdEM0u3_hk-2FmWy
"""

# ============================================
# SENTIMENT ANALYSIS WITH HUGGING FACE IN COLAB
# ============================================

# Step 1: Install the necessary libraries
!pip install -q transformers torch

# Step 2: Import dependencies
from transformers import pipeline

# Step 3: Load a pretrained sentiment analysis model
sentiment_model = pipeline("sentiment-analysis")

# Step 4: Try a few examples
texts = [
    "I love using Google Colab for machine learning!",
    "This is the worst experience I’ve ever had.",
    "The product is okay, but could be improved.",
    "I'm so happy with the results!"
]

# Step 5: Run sentiment analysis
results = sentiment_model(texts)

# Step 6: Display results
for text, result in zip(texts, results):
    print(f"\nText: {text}")
    print(f"Sentiment: {result['label']} (score: {result['score']:.4f})")

# Step 7 (Optional): Analyze your own input (works in Colab)
try:
    custom_text = input("\nEnter a sentence to analyze: ")
    if custom_text.strip():
        custom_result = sentiment_model(custom_text)[0]
        print(f"\nSentiment: {custom_result['label']} (score: {custom_result['score']:.4f})")
    else:
        print("\nNo input provided — skipping custom analysis.")
except EOFError:
    print("\nInput not supported in this environment — skipping custom analysis.")